# GitLab CI configuration for Dependabot
#
# Usage:
# * Set the required global variables used in `./generic-update-script.rb`
#   https://docs.gitlab.com/ee/ci/variables/#variables
#
# * Create a pipeline schedule for each managed repository
#   https://docs.gitlab.com/ee/user/project/pipelines/schedules.html
#
# * Set in the schedule required variables
#
#     PROJECT_PATH = group/repository
#     PACKAGE_MANAGER = bundler,composer,npm_and_yarn
#
# https://github.com/dependabot/dependabot-script
# https://docs.gitlab.com/ee/ci/yaml/

stages:
  - build
  - dependabot

build-image:
  stage: build
  image: docker
  services:
    - name: docker:dind
      command: ["--experimental"]
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: never
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE/dependabot-script || true
    - docker build --cache-from $CI_REGISTRY_IMAGE/dependabot-script --tag $CI_REGISTRY_IMAGE/dependabot-script .
    - docker push $CI_REGISTRY_IMAGE/dependabot-script

.dependabot:
  image: $CI_REGISTRY_IMAGE/dependabot-script
  stage: dependabot
  script:
    - cd /home/dependabot/dependabot-script
    - bundle exec ruby ./generic-update-script.rb
  only:
    - schedules

bundler:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bbundler\b/

pip:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bpip\b/

npm_and_yarn:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /(\bnpm|yarn\b)/

maven:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bmaven\b/

gradle:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bgradle\b/

cargo:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bcargo\b/

hex:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bhex\b/

composer:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bcomposer\b/

nuget:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bnuget\b/

dep:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bdep\b/

go_modules:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bgo_modules\b/

elm:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\belm\b/

submodules:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bsubmodules\b/

docker:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bdocker\b/

terraform:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bterraform\b/

github_actions:
  extends: .dependabot
  only:
    variables:
      - $PACKAGE_MANAGER =~ /\bgithub_actions\b/
